# Genomic reads to process
READS1 : '../test/SRR622457_1-1k.fastq'

# Name of the tested sample
INDIV : 'NA12878'

# Directory where the outputs will be put
DIR: 'run'

# Number of threads used
THREADS : 16

# Directory where the 1KG VCFs are put
DIR_VCF : '../resources/1kg_vcf'

# Reference genome; usually a standard GRC genome
GENOME : '../resources/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna'

# chromosomes included
CHROM : ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y']

# 1KG super populations used to build second pass population genomes
GROUP : ['EUR', 'AMR', 'EAS', 'SAS', 'AFR'] 
    
# mapping quality cutoff to split read into committed and deferred groups
ALN_MAPQ_THRSD : '10' 

### Second-pass genome parameteres
# POP_THRSD: 
#   allele frequency threshold. 0: do not filter by frequency; 0.5: only use major alleles
# POP_STOCHASTIC: 
#   1: stochastic update; 0: deterministic
# POP_BLOCK_SIZE:
#   size of phase-preserving blocks. Set to 1 when doing independent sampling
# POP_USE_LD:
#   1: phase-preserving; 0: independent-sampling
###
### Phase-preserving stochastic update (1kbp-blocks)
    POP_THRSD : 0
    POP_STOCHASTIC : 1
    POP_BLOCK_SIZE : 1000
    POP_USE_LD : 1
### Independent-sampling stochastic update
#     POP_THRSD : 0
#     POP_STOCHASTIC : 1
#     POP_BLOCK_SIZE : 1
#     POP_USE_LD : 0
###  Deterministic major ###
#     POP_THRSD : 0.5
#     POP_STOCHASTIC : 0
#     POP_BLOCK_SIZE : 1
#     POP_USE_LD : 0

# Files specifying 1KG individual-population and population-superpopulation mappings
FAMILY : '../resources/20130606_g1k.ped'
SPOP : '../resources/1kg.superpopulation'

# Chromosome for GRCh38
LENGTH_MAP : '../resources/GRCh38.length_map'
CHROM_MAP : '../resources/GRCh38.chrom_map'

# Paths of software
BCFTOOLS : 'bcftools' # there is a bug with `bcftools consensus` in v1.9, so we recommend using the latest dev version
SAMTOOLS : 'samtools'
LIFTOVER : '../liftover/liftover'
PYTHON : 'python'
DIR_SCRIPTS : '../src'

# Random seed used in the reference flow stochastic reference genome update process and for aligner
RAND_SEED : 0
