# Genomic reads to process
READS1 : '../test/SRR622457_1-1k.fastq'

# Name of the tested sample
INDIV : 'test'

# Directory where the outputs will be put
DIR: 'run'

# Max number of threads used for each rule.
# Note: the total number of threads used is specified by snakemake -j <t>
THREADS : 16

# Whether to use pre-built indexes based on the RandFlow-LD method based on GRCh38 and 1KG
USE_PREBUILT : True

# Whether to sort the output SAM
SORT_SAM : False

# Reference genome; usually a standard GRC genome
GENOME : '../resources/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna'

# Chromosomes included
CHROM : ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y']
# Prefix of a chromosome. Usually set to 'chr' (GRCh38) or '' (hg19)
CHR_PREFIX : 'chr'

# Directory where the 1KG VCFs are put
DIR_VCF : '../resources/1kg_vcf'

# Set prefix and suffix for VCFs
VCF_PREFIX : 'ALL.chr'
VCF_SUFFIX : '.shapeit2_integrated_snvindels_v2a_27022019.GRCh38.phased.vcf.gz'

# 1KG super populations used to build second pass population genomes
GROUP : ['EUR', 'AMR', 'EAS', 'SAS', 'AFR'] 

# mapping quality cutoff to split read into committed and deferred groups
ALN_MAPQ_THRSD : '10' 

### Second-pass genome parameteres
# POP_THRSD: 
#   allele frequency threshold. 0: do not filter by frequency; 0.5: only use major alleles
# POP_STOCHASTIC: 
#   1: stochastic update; 0: deterministic
# POP_BLOCK_SIZE:
#   size of phase-preserving blocks. Set to 1 when doing independent sampling
# POP_USE_LD:
#   1: phase-preserving; 0: independent-sampling
###
### Phase-preserving stochastic update (1kbp-blocks)
POP_THRSD : 0
POP_STOCHASTIC : 1
POP_BLOCK_SIZE : 1000
POP_USE_LD : 1
### Independent-sampling stochastic update
#     POP_THRSD : 0
#     POP_STOCHASTIC : 1
#     POP_BLOCK_SIZE : 1
#     POP_USE_LD : 0
###  Deterministic major ###
#     POP_THRSD : 0.5
#     POP_STOCHASTIC : 0
#     POP_BLOCK_SIZE : 1
#     POP_USE_LD : 0

# Files specifying 1KG individual-population and population-superpopulation mappings
FAMILY : '../resources/20130606_g1k.ped'
SPOP : '../resources/1kg.superpopulation'

# Chromosome for GRCh38
LENGTH_MAP : '../resources/GRCh38.length_map'
CHROM_MAP : '../resources/GRCh38.chrom_map'

# Paths of software
BCFTOOLS : 'bcftools' # there is a bug with `bcftools consensus` in v1.9, so we recommend using the latest dev version
SAMTOOLS : 'samtools'
LEVIOSAM : '../levioSAM/leviosam'
PYTHON : 'python'
DIR_SCRIPTS : '../src'

# Random seed used in the reference flow stochastic reference genome update process and for aligner
RAND_SEED : 0
